# Generated by Django 5.2.17 on 2026-09-22 08:26

import django.db.models.deletion
import django.utils.timezone
import polls.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200, verbose_name='soru')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='aciklama')),
                ('status', models.CharField(choices=[('open', 'acik'), ('closed', 'kapali')], default='open', max_length=8, verbose_name='durum')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='olusturulma')),
                ('closes_at', models.DateTimeField(blank=True, default=polls.models.default_closes_at, null=True, verbose_name='kapanis')),
                ('allow_guest_votes', models.BooleanField(default=True, help_text='Kapatilirsa yalnizca uyeler oy verebilir.', verbose_name='ziyaretci oyuna acik')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='olusturan')),
            ],
            options={
                'verbose_name': 'anket',
                'verbose_name_plural': 'anketler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=120, verbose_name='secenek')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='sira')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll', verbose_name='anket')),
            ],
            options={
                'verbose_name': 'secenek',
                'verbose_name_plural': 'secenekler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_token', models.UUIDField(blank=True, null=True, verbose_name='ziyaretci anahtari')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='ip ozeti')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='olusturulma')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option', verbose_name='secenek')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll', verbose_name='anket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='uye')),
            ],
            options={
                'verbose_name': 'oy',
                'verbose_name_plural': 'oylar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['-created_at'], name='polls_poll_created_fdd0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['status', '-created_at'], name='polls_poll_status_1abc97_idx'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('poll', 'order'), name='uniq_option_order_per_poll'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', 'created_at'], name='polls_vote_poll_id_579149_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['ip_hash', 'created_at'], name='polls_vote_ip_hash_f0e97c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('poll', 'user'), name='uniq_vote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('voter_token__isnull', False)), fields=('poll', 'voter_token'), name='uniq_vote_per_token'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('voter_token__isnull', False), _connector='OR'), name='vote_has_identity'),
        ),
    ]
